const data = {
  products: [
    {
      name: 'Nike Slim',
      slug: 'nike-slim',
      category: 'shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality',
    },
    {
      name: 'Nike Pant',
      slug: 'nike-pant',
      category: 'shirts',
      image: 'images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality',
    },
    {
      name: 'Nike Track',
      slug: 'nike-track',
      category: 'shirts',
      image: 'images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality',
    },
    {
      name: 'Nike Shorts',
      slug: 'nike-shorts',
      category: 'shirts',
      image: 'images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality',
    },
  ],
};
export default data;
